#define MAX_DEFERRED_EXECUTORS 16
#define COMBO_COUNT 105

#define TAPPING_TERM 300
#define COMBO_TERM 35

#define ONESHOT_TIMEOUT 5000

//#define SMTD_TIMEOUT_TAP 300
#define SMTD_GLOBAL_RELEASE_TERM 20